/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Addon } from "./Addon";
import { AddonCountArgs } from "./AddonCountArgs";
import { AddonFindManyArgs } from "./AddonFindManyArgs";
import { AddonFindUniqueArgs } from "./AddonFindUniqueArgs";
import { CreateAddonArgs } from "./CreateAddonArgs";
import { UpdateAddonArgs } from "./UpdateAddonArgs";
import { DeleteAddonArgs } from "./DeleteAddonArgs";
import { OrderItemFindManyArgs } from "../../orderItem/base/OrderItemFindManyArgs";
import { OrderItem } from "../../orderItem/base/OrderItem";
import { PriceFindManyArgs } from "../../price/base/PriceFindManyArgs";
import { Price } from "../../price/base/Price";
import { Product } from "../../product/base/Product";
import { AddonService } from "../addon.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Addon)
export class AddonResolverBase {
  constructor(
    protected readonly service: AddonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Addon",
    action: "read",
    possession: "any",
  })
  async _addonsMeta(
    @graphql.Args() args: AddonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Addon])
  @nestAccessControl.UseRoles({
    resource: "Addon",
    action: "read",
    possession: "any",
  })
  async addons(@graphql.Args() args: AddonFindManyArgs): Promise<Addon[]> {
    return this.service.addons(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Addon, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Addon",
    action: "read",
    possession: "own",
  })
  async addon(
    @graphql.Args() args: AddonFindUniqueArgs
  ): Promise<Addon | null> {
    const result = await this.service.addon(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Addon)
  @nestAccessControl.UseRoles({
    resource: "Addon",
    action: "create",
    possession: "any",
  })
  async createAddon(@graphql.Args() args: CreateAddonArgs): Promise<Addon> {
    return await this.service.createAddon({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Addon)
  @nestAccessControl.UseRoles({
    resource: "Addon",
    action: "update",
    possession: "any",
  })
  async updateAddon(
    @graphql.Args() args: UpdateAddonArgs
  ): Promise<Addon | null> {
    try {
      return await this.service.updateAddon({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Addon)
  @nestAccessControl.UseRoles({
    resource: "Addon",
    action: "delete",
    possession: "any",
  })
  async deleteAddon(
    @graphql.Args() args: DeleteAddonArgs
  ): Promise<Addon | null> {
    try {
      return await this.service.deleteAddon(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [OrderItem], { name: "orderItems" })
  @nestAccessControl.UseRoles({
    resource: "OrderItem",
    action: "read",
    possession: "any",
  })
  async findOrderItems(
    @graphql.Parent() parent: Addon,
    @graphql.Args() args: OrderItemFindManyArgs
  ): Promise<OrderItem[]> {
    const results = await this.service.findOrderItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Price], { name: "prices" })
  @nestAccessControl.UseRoles({
    resource: "Price",
    action: "read",
    possession: "any",
  })
  async findPrices(
    @graphql.Parent() parent: Addon,
    @graphql.Args() args: PriceFindManyArgs
  ): Promise<Price[]> {
    const results = await this.service.findPrices(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "any",
  })
  async getProduct(@graphql.Parent() parent: Addon): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
